#!/usr/bin/env bash
# =============================================================================
# MAGMA v1.10 — cell-type specificity set enrichment (cortical development)
# =============================================================================
# Command flags as used in the study.
# Set annotations: top 10 % most specific genes per cell type and per
# developmental stage (generated by EWCE_generateCTD.R).
# Conditioning on gene size/density, sample size and inverse MAF.
# =============================================================================

STAGE=Mean_SubCellType   # also: Adult, trimester2nd/3rd, years0_1, years1_2, ...

magma \
    --gene-results sorted_meta_mdd2023diverse_EAS_Neff-ourHan_l-r_dosage_allCovar-TPMI_mdd.Diff-Model.I85.MAGMAdefault.entrezID.genes.raw \
    --set-annot /path/to/cortical_development/${STAGE}/MAGMA/top10.txt \
    --out DEP_EAS_NCrevison_dosage_allCovar_I85-cortical_development_${STAGE}.enrich

# Same for the MTAG (DEP-SZ-BD-INSO) gene results:
magma \
    --gene-results MTAG_EAS_DEP_NCrevision_dosage_add_TPMImdd-SZ_INSO_BD.MAGMAdefault.entrezID.genes.raw \
    --set-annot /path/to/cortical_development/${STAGE}/MAGMA/top10.txt \
    --out MTAG_EAS_DEP_NCrevision_dosage_add_TPMImdd-SZ_INSO_BD-cortical_development_${STAGE}.enrich
